<a href="https://colab.research.google.com/github/nidheesh-kadem/SP500/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [89]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [90]:
scalar.ndim

0

In [91]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [92]:
vector.ndim

1

In [93]:
matrix = tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [94]:
matrix.ndim

2

In [95]:
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [10., .7]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 7. , 10. ],
       [10. ,  0.7]], dtype=float16)>

In [96]:
another_matrix.ndim

2

In [97]:
tensor = tf.constant([[[10,7],
                       [7,10]],
                      [[5,10],
                       [10,5]],
                       [[4,5],
                        [5,4]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]],

       [[ 5, 10],
        [10,  5]],

       [[ 4,  5],
        [ 5,  4]]], dtype=int32)>

In [98]:
tensor.ndim

3

In [99]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [100]:
random_tensor_1 = tf.random.Generator.from_seed(45)
random_tensor_1 = random_tensor_1.uniform([3,3])
random_tensor_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.86540747, 0.8862978 , 0.27795732],
       [0.8857763 , 0.2179842 , 0.29115117],
       [0.03953862, 0.8136791 , 0.8139852 ]], dtype=float32)>

In [101]:
random_tensor_2 = tf.random.Generator.from_seed(45)
random_tensor_2 = random_tensor_2.normal([3,3])
random_tensor_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.3522796 ,  0.40621263, -1.0523509 ],
       [ 1.2054597 ,  1.6874489 , -0.4462975 ],
       [-2.3410842 ,  0.99009085, -0.0876323 ]], dtype=float32)>

### In a uniform distribution all outcomes are equally likely to occur, on a normal distribution all outcomes close to the mean and more likely to occur.

In [102]:
random_tensor_3 = tf.random.Generator.from_seed(45)
random_tensor_3 = random_tensor_3.normal([3,2])
random_tensor_3

# shuffle random_tensor_3

shuffeled_tensor = tf.random.shuffle(random_tensor_3)

random_tensor_3, shuffeled_tensor

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.3522796 ,  0.40621263],
        [-1.0523509 ,  1.2054597 ],
        [ 1.6874489 , -0.4462975 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0523509 ,  1.2054597 ],
        [-0.3522796 ,  0.40621263],
        [ 1.6874489 , -0.4462975 ]], dtype=float32)>)

In [103]:
random_tensor_4 = tf.random.Generator.from_seed(45)
random_tensor_4 = random_tensor_4.normal([3,2])


# shuffle random_tensor_4 with seed 40
# shuffled tensor with a seed will not changed the order.

tf.random.set_seed(40)
shuffeled_tensor = tf.random.shuffle(random_tensor_4)

random_tensor_4, shuffeled_tensor

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.3522796 ,  0.40621263],
        [-1.0523509 ,  1.2054597 ],
        [ 1.6874489 , -0.4462975 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0523509 ,  1.2054597 ],
        [-0.3522796 ,  0.40621263],
        [ 1.6874489 , -0.4462975 ]], dtype=float32)>)

In [104]:
tf.ones([2,2])
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

What is the difference between NumPy arrays and TensorFlow tensors? TensorFlow tensors can be run on GPU.  

COnvert a numpy array to a tensor

In [105]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [106]:
# we change a NumPy array to a TensorFlow Tensor we want. We can also change the shape of the tensor but it should add up to the total number of elements.

numpy_to_constant = tf.constant(numpy_A)
numpy_to_variable = tf.Variable(numpy_A)

numpy_to_constant, numpy_to_variable

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [107]:
change_shape_numpy_to_constant = tf.constant(numpy_A, shape=(3,8))
change_shape_numpy_to_constant_2 = tf.constant(numpy_A, shape=(2, 3, 4))

# cannot change shape of variable
# change_shape_numpy_to_variable = tf.Variable(numpy_A, shape=(2, 3, 4))

change_shape_numpy_to_constant, change_shape_numpy_to_constant_2

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [108]:
change_shape_numpy_to_constant.ndim


2

In [109]:
change_shape_numpy_to_constant_2.ndim

3

In [110]:
# creating a rank 4 tensor

rank_4_tensor = tf.zeros(shape=[2,3,4,5])

rank_4_tensor.ndim, rank_4_tensor, rank_4_tensor[0], rank_4_tensor.shape, tf.size(rank_4_tensor)

(4,
 <tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0.,

In [111]:
print("Datatype of the tensor:", rank_4_tensor.dtype)
print("Number of dimentions in a tensor:", rank_4_tensor.ndim)
print("Shape of the tensor:", rank_4_tensor.shape)
print("Elements on the 0 axis:", rank_4_tensor.shape[0])
print("Elements ont the last axis:", rank_4_tensor.shape[-1])
print("Total number of tensors:", tf.size(rank_4_tensor).numpy())

Datatype of the tensor: <dtype: 'float32'>
Number of dimentions in a tensor: 4
Shape of the tensor: (2, 3, 4, 5)
Elements on the 0 axis: 2
Elements ont the last axis: 5
Total number of tensors: 120


In [112]:
# Tensors can be indexed like python list.

rank_4_tensor[:1,:,:,:]

<tf.Tensor: shape=(1, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [113]:
# Create a random rank 2 tensor.

rank_2_tensor = tf.random.Generator.from_seed(45)
rank_2_tensor = rank_2_tensor.normal([2,2])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ]], dtype=float32)>

In [114]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.40621263, 1.2054597 ], dtype=float32)>

In [115]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.3522796 ],
        [ 0.40621263]],

       [[-1.0523509 ],
        [ 1.2054597 ]]], dtype=float32)>

In [116]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.3522796 ],
        [ 0.40621263]],

       [[-1.0523509 ],
        [ 1.2054597 ]]], dtype=float32)>

In [117]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-0.3522796 ,  0.40621263],
        [-1.0523509 ,  1.2054597 ]]], dtype=float32)>

In [118]:
# using basic operations on tensors +, -, *, /

operation_tensor = tf.random.Generator.from_seed(69)
operation_tensor = operation_tensor.normal([2,2])

operation_tensor, operation_tensor + 1, operation_tensor - 1, operation_tensor * 10, operation_tensor / 2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.29164317,  1.4531525 ],
        [-0.8223833 , -1.3446563 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.2916431 ,  2.4531527 ],
        [ 0.17761672, -0.34465635]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.70835686,  0.45315254],
        [-1.8223833 , -2.3446565 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[  2.9164317,  14.531526 ],
        [ -8.223833 , -13.446564 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.14582159,  0.72657627],
        [-0.41119164, -0.6723282 ]], dtype=float32)>)

In [119]:
tf.multiply(operation_tensor, 10), tf.add(operation_tensor, 1), tf.subtract(operation_tensor, 1), tf.divide(operation_tensor, 2)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[  2.9164317,  14.531526 ],
        [ -8.223833 , -13.446564 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.2916431 ,  2.4531527 ],
        [ 0.17761672, -0.34465635]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.70835686,  0.45315254],
        [-1.8223833 , -2.3446565 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.14582159,  0.72657627],
        [-0.41119164, -0.6723282 ]], dtype=float32)>)

In [120]:
# matrix multiplication in tensorflow
tensor = tf.constant([[10,7],
                      [3,4]])

tf.matmul(tensor,tensor), tensor @ tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [121]:
# we need to perform matrix multiplication
# inner dimentions need to match and the resulting matrix is the outer dimentions

x = tf.constant([[1,2],
                [3,4],
                [5,6]])
y = tf.constant([[7,8],
                [9,10],
                [11,12]])

# tf.matmul(x, y) and x @ y, which are matrix multiplications would not work as it is 3x2 and 3x2. We want the inner dimentions to match.
# we msut reshape x or y, here we reshape y to be 2x3. The multiplication will work 3x2 and 2x3

tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [122]:
# After the change now it will work
tf.matmul(x, tf.reshape(y, shape=(2,3))), x @ tf.reshape(y, shape=(2,3))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [123]:
tf.reshape(x, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [124]:
# When we change x instead of y, the product of matrix multiplication will change
tf.matmul(tf.reshape(x, shape=(2,3)), y), tf.reshape(x, shape=(2,3)) @ y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]], dtype=int32)>)

In [125]:
# tf.reshape and tf.transpose are two different opperations we can perform a matrix
reshape_tensor = tf.reshape(x, shape=(2,3))

transpose_tensor = tf.transpose(x)

x, reshape_tensor, transpose_tensor

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [126]:
# We can perform matrix multiplication with transpose
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [127]:
# reduced precision the default value is int32 and float32, we can also use int16 and float16 which would use less memory.
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[5.1,6.2],
                 [7.3,8.4]])
a.dtype, b.dtype

(tf.int32, tf.float32)

In [128]:
c = tf.cast(a, dtype=tf.int16)
d = tf.cast(b, dtype=tf.float16)

c.dtype, d.dtype

(tf.int16, tf.float16)

In [129]:
# Aggregating a tensor: condensing them from multiple amount of values to smaller values

# Turn all the negitive numbers into positive numbers

negative_tensor = tf.constant([[-1,-2],
                               [-3, -4]])

absolute_tensor = tf.abs(negative_tensor)

negative_tensor, absolute_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-1, -2],
        [-3, -4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [130]:
# find the min, max, mean and sum of a tensor

random_tensor = tf.random.Generator.from_seed(420)
random_tensor_float = random_tensor.normal([2,2])
random_tensor_int = tf.cast(random_tensor_float, dtype = tf.int32)

random_tensor_min = tf.reduce_min(random_tensor_int)
random_tensor_max = tf.reduce_max(random_tensor_int)
random_tensor_mean = tf.reduce_mean(random_tensor_int)
random_tensor_sum = tf.reduce_sum(random_tensor_int)
random_tensor_variance = tf.math.reduce_variance(random_tensor_float)
random_tensor_standard_deviation = tf.math.reduce_std(random_tensor_float)

random_tensor_float, random_tensor_int, random_tensor_min, random_tensor_max, random_tensor_mean, random_tensor_sum, random_tensor_variance, random_tensor_standard_deviation

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.6356361 , -0.08795371],
        [-1.3398387 , -0.00641572]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0,  0],
        [-1,  0]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5118872>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.7154629>)

In [144]:
# Finding the positional maximum and minimum
tf.random.set_seed(42)
positional_tensor = tf.random.uniform([50])

positional_tensor, tf.argmax(positional_tensor), positional_tensor[tf.argmax(positional_tensor)], tf.reduce_max(positional_tensor)

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [147]:
tf.argmin(positional_tensor), positional_tensor[tf.argmin(positional_tensor)], tf.reduce_min(positional_tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)